### ISSUE TITLE
Protect the API Key

### ISSUE THREAD

**Issue by pandosme** [bisand/node-red-contrib-tibber-api#36]
The API key should be stored in a configuration node as credentials.  Now there is a risk of exposing your key if you export and send/publish an example flow.

**Comment by bisand** [comment]
You are right about that. I will start the work right away. Thanks.

**Comment by pandosme** [comment]
Great!

**Comment by bisand** [comment]
Migrated API key to Credentials and renamed it to Access Token (accessToken). The transition should be seamless, and any stored API keys should be automatically converted to Access Token Credentials.
