### ISSUE TITLE
Tibber-feed not working

### ISSUE THREAD

**Issue by pandosme** [bisand/node-red-contrib-tibber-api#37]
I cannot get any data from tibber-feed.  I only get disconnect/reconnect every 30 seconds.  Or, am I doing something wrong?

**Comment by bisand** [comment]
Are you trying with the demo token or your personal token? The connection should automatically reconnect whenever the connection is lost. It could be that the Tibber Pulse is not publishing data. It is required to have Tibber Pulse correctly installed in your power meter in order to have the feed working correctly. (Check that in the Tibber app).

First try it out with the demo token. If that is working, you should be able to receive data with your personal token, if Tibber Pulse is transmitting.

Please provide some logging output to make it easier to see what the problem could be.

Thanks!

**Comment by pandosme** [comment]
The demo flows works fine.  As soon as I set my API key and home ID I get disconnected every 30 seconds. "Connection timed out after 30000 ms. Reconnecting..."

My API key and Home ID works fine for other GraphQL-queries.

My tibber app on my Andorid states (Swedish) "Väntar på att ditt nätbolag ska skicka din första förbrukning)".   I don't know if this has any impact on my data delivery.

**Comment by bisand** [comment]
This is probably the reason you are not receiving any data. You can use your API key together with all the other basic queries, but when it comes to the feed, the data needs to be available from Tibber Pulse before you can see it in the app or via the tibber api node-red client.

The api client will try to reconnect every 30 seconds until it receives any data.

If no data is available in the Tibber app either, you should contact Tibber support. Hopefully they can help you. Let me know if you still have connectivity issues after you have received data in the app.

**Comment by pandosme** [comment]
Thanks.  will investigate my setup.  Btw, you have a number of interesting repositories,  I think we have a lot in common.  Please contact me at  <mailto:admin@pandos.me> admin@pandos.me.

 

/Pandos

 

Från: André Biseth <notifications@github.com> 
Skickat: den 13 mars 2020 22:56
Till: bisand/node-red-contrib-tibber-api <node-red-contrib-tibber-api@noreply.github.com>
Kopia: Pandos Me <fred@juhlin.me>; Author <author@noreply.github.com>
Ämne: Re: [bisand/node-red-contrib-tibber-api] Tibber-feed not working (#37)

 

This is probably the reason you are not receiving any data. You can use your API key together with all the other basic queries, but when it comes to the feed, the data needs to be available from Tibber Pulse before you can see it in the app or via the tibber api node-red client.

The api client will try to reconnect every 30 seconds until it receives any data.

If no data is available in the Tibber app either, you should contact Tibber support. Hopefully they can help you. Let me know if you still have connectivity issues after you have received data in the app.
