### ISSUE TITLE
currentPhase1 was Replaced by currentL1 but it is not removed from the code

### ISSUE THREAD

**Issue by Sungtroll** [bisand/node-red-contrib-tibber-api#43]
please take out from the code because it can not be deselected and therefore always exists.
         "currentPhase1": "1",
        "currentPhase2": "1",
        "currentPhase3": "1",

Only the current setting below is working.
        "currentL1": false,
        "currentL2": false,
        "currentL3": false,

**Comment by bisand** [comment]
The deprecated fields currentPhaseX are now removed from the code and will no longer appear in the feed. Upgrade to latest version (2.0.0) to apply the changes.

Thanks for reminding me @Sungtroll
