### ISSUE TITLE
Suggestion example for use in grafana

### ISSUE THREAD

**Issue by Sungtroll** [bisand/node-red-contrib-tibber-api#47]
I included energy prices with powerline transmission fee and compared with a couple of friends energy usage hour by hour consumption.
Added tomorrows energy prices so easy to plan heavy power usage and avoid high energy prices.
@bisand Please feel free to delete this post after read because it is not a tibber-api issue.

![Get tomorrow](https://user-images.githubusercontent.com/37970110/112357241-9f14ee00-8ccf-11eb-94f5-31572114f93c.png)
![Tomorrow energy prices](https://user-images.githubusercontent.com/37970110/112357269-a3d9a200-8ccf-11eb-8959-442278b16a9f.PNG)

**Comment by bisand** [comment]
I'll leave it open for now. We can add your suggestion to the examples included in the Node-Red module.
