### ISSUE TITLE
Cannot create property 'httpCode' on string 'GraphQL queries must be strings.'

### ISSUE THREAD

**Issue by cod3gen** [bisand/node-red-contrib-tibber-api#55]
Hi,

I am currently not able to fetch tibber data, returns following error:
```
29 Mar 18:24:00 - [red] Uncaught Exception:
29 Mar 18:24:00 - [error] TypeError: Cannot create property 'httpCode' on string 'GraphQL queries must be strings.'
    at IncomingMessage.<anonymous> (/config/node-red/node_modules/tibber-api/src/nodes/TibberQuery.ts:98:46)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

This is on Node-RED v11.1.1 @ HA Core 2022.3.8. Anyone know of a fix for this? :)

**Comment by bisand** [comment]
I will do some testing on my side to see if I can reproduce it. @cod3gen Can you please provide the content of the payload you are trying to inject, if any.
Thanks!

**Comment by cod3gen** [comment]
> I will do some testing on my side to see if I can reproduce it. @cod3gen Can you please provide the content of the payload you are trying to inject, if any. Thanks!

Thanks.
cron-plus is serving pulses to fetch prices to pass on to power-saver. Tried to send cron-plus`s payload to both msg.payload and just msg.xx without any differences.
![tibber_query](https://user-images.githubusercontent.com/14929298/160884983-273cbe1b-3cd1-4db4-b342-b16bd2bc1818.png)

**Comment by bisand** [comment]
I suspect that the cron-plus node is injecting an unsupported payload to the Tibber-Query. This node only support GraphQL queries in the payload like the following example:

`{viewer{homes{id size appNickname appAvatar address{address1 address2 address3 postalCode city country latitude longitude}}}}`

Try that and se if this solves the problem.

**Comment by bisand** [comment]
Hi,
I have just updated to a new version that shoud give you a better error message in case this happens again. The ne version is 2.6.2.
Relates to #57

**Comment by bisand** [comment]
Should be resolved by now. Please report back if you still experience problems.
