### ISSUE TITLE
feature request: Adding proxy use

### ISSUE THREAD

**Issue by nevtag** [bisand/node-red-contrib-tibber-api#56]
Hi,
I use a proxy in my network.
Unfortunately, the tibber-api did not use the proxy env settings. Node red did use the env settings.
Please could you add to use the proxy env settings, or use the node http-request, that has a proxy parameter.
![node-http-request](https://user-images.githubusercontent.com/1618658/161203574-164c2b10-87f4-4a14-a72e-2b8b80523bf0.png)

**Comment by rvalle** [comment]
Same here

**Comment by bisand** [comment]
Just released a new version of node-red-contrib-tibber-api (v5.2.0) to npm that includes the changes from @rvalle's [pull request](https://github.com/bisand/node-red-contrib-tibber-api/pull/74).
Follow the instructions there to introduce proxy support for your Tibber flows.
