### ISSUE TITLE
Tibber Query causes nodered fatal crash if invalid response from Tibber

### ISSUE THREAD

**Issue by noppo** [bisand/node-red-contrib-tibber-api#57]
Today Tibber servers are down or not replying as normal. Using the Tibber Query node, if there is a non-normal response, it causes Node Red to have a fatal crash and stop. Running Node Red in docker displays log a shown below. 

I tried to add a "Catch: all" node to my flow but it is not possible to catch this error. Tried also add nodes at after Tibber query node to correct for errors, but the flow never reaches this node. It seems this error must be fixed within the Tibber query node?

5 Apr 21:36:58 - [red] Uncaught Exception:
5 Apr 21:36:58 - [error] TypeError: Cannot create property 'httpCode' on string 'Too many requests'
    at IncomingMessage.<anonymous> (/data/node_modules/tibber-api/lib/src/nodes/TibberQuery.js:108:47)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@2.2.2 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1

A few days ago I saw this error. Different error message, but same result, Node Red crashes.
31 Mar 13:45:48 - [red] Uncaught Exception:
31 Mar 13:45:48 - [error] TypeError: Cannot create property 'httpCode' on string '<html><head><title>502 Bad Gateway</title></head><body><center><h1>502 Bad Gateway</h1></center></body></html>'
    at IncomingMessage.<anonymous> (/data/node_modules/tibber-api/lib/src/nodes/TibberQuery.js:108:47)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@2.2.2 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1

**Comment by bisand** [comment]
That's not good. I will investigate and get backt to you as soon as I can.

**Comment by Sungtroll** [comment]
i did not have any problems at all today using many different accounts and not a single dataloss.

**Comment by noppo** [comment]
I did som more investigation. I tracked down where in the code it fails:

I added consle.error in the response section of the code TibberQuery.js 
`                        if (res.statusCode >= 200 && res.statusCode < 300) {
                            resolve(response.data ? response.data : response);
                        }
                        else {
                            console.error("JEK problem with request");
                            response.httpCode = res.statusCode;
                            response.statusCode = res.statusCode;
                            response.statusMessage = res.statusMessage;
                            reject(response);`

And this is the last thing node red outputs before fatally crashing:

> JEK problem with request
> 28 Apr 16:03:52 - [red] Uncaught Exception:
> 28 Apr 16:03:52 - [error] TypeError: Cannot create property 'httpCode' on string "<html>
><head><title>504 Gateway Time-out</title></head>
><body>
><center><h1>504 Gateway Time-out</h1></center>
></body>
> </html>

>    at IncomingMessage.<anonymous> (/data/node_modules/tibber-api/lib/src/nodes/TibberQuery.js:109:47)
>    at IncomingMessage.emit (events.js:412:35)
>    at endReadableNT (internal/streams/readable.js:1334:12)
>    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by noppo** [comment]
By the way it seems this error applies to all HTTP error codes. I have seen several different ones like '429 Too Many Requests'
I have tuned down the flow to run only run every 30 minutes. (previously 5 minutes). Now the error does not happen as often. But still node-red crashes once a week or so.

**Comment by bisand** [comment]
Sorry for the late response! I will take a look at the problems and see what I can do to fix it.

**Comment by osvedman** [comment]
I encountered this exact problem today with an HTTP 503 error. Thank you for looking into it, @bisand!

**Comment by hflatoey** [comment]
Been using this node for a like 2 months and bam yesterday it crashes my Node-Red and it get's into a restart loop.

9 Jun 07:42:26 - [red] Uncaught Exception:
9 Jun 07:42:26 - [error] TypeError: Cannot create property 'httpCode' on string '<html>

<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
</body>
</html>
'
at IncomingMessage.<anonymous> (/data/node_modules/tibber-api/lib/src/nodes/TibberQuery.js:108:47)
at IncomingMessage.emit (node:events:539:35)
at endReadableNT (node:internal/streams/readable:1344:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by Blodstrupmo1** [comment]
Same problem here, crashes nodered docker 2times an hour during tibbers api outage.

**Comment by bisand** [comment]
Hi all,
Sorry for the late response. I have been a little bit occupied in my daily job and haven't been able to prioritize this for a while.
I have just released an update that includes improved handling of TibberQuery responses. Hopefully this fixes the problems you have been experiencing. The new version is 2.6.1.

**Comment by CoronaExtra** [comment]
> Today Tibber servers are down or not replying as normal. Using the Tibber Query node, if there is a non-normal response, it causes Node Red to have a fatal crash and stop. Running Node Red in docker displays log a shown below.
> 
> I tried to add a "Catch: all" node to my flow but it is not possible to catch this error. Tried also add nodes at after Tibber query node to correct for errors, but the flow never reaches this node. It seems this error must be fixed within the Tibber query node?
> 
> 5 Apr 21:36:58 - [red] Uncaught Exception: 5 Apr 21:36:58 - [error] TypeError: Cannot create property 'httpCode' on string 'Too many requests' at IncomingMessage. (/data/node_modules/tibber-api/lib/src/nodes/TibberQuery.js:108:47) at IncomingMessage.emit (events.js:412:35) at endReadableNT (internal/streams/readable.js:1334:12) at processTicksAndRejections (internal/process/task_queues.js:82:21) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! node-red-docker@2.2.2 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"` npm ERR! Exit status 1
> 
> A few days ago I saw this error. Different error message, but same result, Node Red crashes. 31 Mar 13:45:48 - [red] Uncaught Exception: 31 Mar 13:45:48 - [error] TypeError: Cannot create property 'httpCode' on string '<title>502 Bad Gateway</title>
> 
> # 502 Bad Gateway
> '
> at IncomingMessage. (/data/node_modules/tibber-api/lib/src/nodes/TibberQuery.js:108:47)
> at IncomingMessage.emit (events.js:412:35)
> at endReadableNT (internal/streams/readable.js:1334:12)
> at processTicksAndRejections (internal/process/task_queues.js:82:21)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-red-docker@2.2.2 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
> npm ERR! Exit status 1



> Today Tibber servers are down or not replying as normal. Using the Tibber Query node, if there is a non-normal response, it causes Node Red to have a fatal crash and stop. Running Node Red in docker displays log a shown below.
> 
> I tried to add a "Catch: all" node to my flow but it is not possible to catch this error. Tried also add nodes at after Tibber query node to correct for errors, but the flow never reaches this node. It seems this error must be fixed within the Tibber query node?
> 
> 5 Apr 21:36:58 - [red] Uncaught Exception: 5 Apr 21:36:58 - [error] TypeError: Cannot create property 'httpCode' on string 'Too many requests' at IncomingMessage. (/data/node_modules/tibber-api/lib/src/nodes/TibberQuery.js:108:47) at IncomingMessage.emit (events.js:412:35) at endReadableNT (internal/streams/readable.js:1334:12) at processTicksAndRejections (internal/process/task_queues.js:82:21) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! node-red-docker@2.2.2 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"` npm ERR! Exit status 1
> 
> A few days ago I saw this error. Different error message, but same result, Node Red crashes. 31 Mar 13:45:48 - [red] Uncaught Exception: 31 Mar 13:45:48 - [error] TypeError: Cannot create property 'httpCode' on string '<title>502 Bad Gateway</title>
> 
> # 502 Bad Gateway
> '
> at IncomingMessage. (/data/node_modules/tibber-api/lib/src/nodes/TibberQuery.js:108:47)
> at IncomingMessage.emit (events.js:412:35)
> at endReadableNT (internal/streams/readable.js:1334:12)
> at processTicksAndRejections (internal/process/task_queues.js:82:21)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-red-docker@2.2.2 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
> npm ERR! Exit status 1

Hi ! I saw somewhat same problem today:

15 Jun 11:50:43 - [red] Uncaught Exception:
15 Jun 11:50:43 - [error] TypeError: Cannot create property 'httpCode' on string '<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
'
    at IncomingMessage.<anonymous> (/data/node_modules/tibber-api/src/nodes/TibberQuery.ts:98:46)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by noppo** [comment]
Thank you taking the time to create a fix. I have now installed version 2.6.2. Looking good so far! I will update later when it has been running for while.

**Comment by bisand** [comment]
> 

@CoronaExtra did you experience this after upgrading to 2.6.2?

**Comment by bisand** [comment]
Hi all,
I did a few more improvements to the error handling in [node-red-contrib-tibber-api](https://github.com/bisand/node-red-contrib-tibber-ap). and also spent some time testing and improving the [tibber-api](https://github.com/bisand/tibber-api/) dependency. The new version [2.7.0](https://www.npmjs.com/package/node-red-contrib-tibber-api) should be more stable and be able to handle network dropout without bringing down Node-Red. Please install the new version and see if this makes the system more stable.
Thanks for being patient!

**Comment by bisand** [comment]
Connection issues should be resolved. Please report back if you still experience problems.
Closing
