### ISSUE TITLE
Newest versions of Node is not supported

### ISSUE THREAD

**Issue by ThermIQ** [bisand/node-red-contrib-tibber-api#58]
Trying to install on latest version of Node fails with following message:

2022-07-22T14:05:20.313Z [err] notsup Required: {"node":">=10 <15"}
2022-07-22T14:05:20.313Z [err] npm ERR! notsup Actual:   {"npm":"8.13.2","node":"v18.6.0"}

**Comment by bisand** [comment]
The intention of Node-RED team is to support the [maintenance and active LTS releases of Node.js](https://nodered.org/docs/faq/node-versions). They generally do not recommend using odd numbers of Node.js

**Comment by ThermIQ** [comment]
I was using version 18

**Comment by bisand** [comment]
18 is not an LTS version, but I can take a look at it and see if it is possible to support a non LTS version 😊

**Comment by bisand** [comment]
It should now support NodeJS 18
