### ISSUE TITLE
Some null values in the JSON data

### ISSUE THREAD

**Issue by martinsund999** [bisand/node-red-contrib-tibber-api#59]
Since 2022-09-27 there is some null values in the JSON data. Im not sure if it something wrong in the node red plugin or at Tibber.

For example, the accumulatedCost used to contain the cost. Now it's null.

![image](https://user-images.githubusercontent.com/2984005/192746167-150aa53c-bcaa-42fc-a402-240bc4a19bde.png)

**Comment by osvedman** [comment]
I think this is on the Tibber side.

If you go to https://developer.tibber.com/explorer , load up your personal token, and try the example query "Real time subscription", you'll see the same fields return Null there.

I'm going to send Tibber a message about this and see what they say.

**Comment by martinsund999** [comment]
Great! I have sent Tibber an email also. Hope they can fix it asap, my graphs in Grafana gets f@cked up.

**Comment by osvedman** [comment]
Looks like it's working again today. I haven't heard back from Tibber yet, though.

**Comment by martinsund999** [comment]
Great! Maybe they have seen our emails. It's working again!

**Comment by osvedman** [comment]
@martinsund999 As this issue was identified to be with Tibber and not this node, I think you can close this issue now :)
