### ISSUE TITLE
Breaking change in websocket subscription (December 2022)

### ISSUE THREAD

**Issue by Dunnenj** [bisand/node-red-contrib-tibber-api#60]
The following is on the Developer site of the Tibber API [https://developer.tibber.com/docs/overview#Breaking%20change%20in%20websocket%20subscriptions%20December%202022].

I hope this is take into account before the break will happen.

Breaking change in websocket subscriptions December 2022
This API initally supported Graphql websocket subscriptions using [graphql-ws](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md) sub-protocol. However, that library is [archived and no longer maintained](https://github.com/apollographql/subscriptions-transport-ws). Thus, on March 31th 2022 support for [graphql-transport-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) sub-protocol was added.

Support for old protocol will be removed during December 2022. Also, at the same time, the URL for connecting to websocket server changes. Previously the connection could be established at wss://api.tibber.com/v1-beta/gql/subscriptions. After the change the URL must be queried via Graphql:

**Comment by bisand** [comment]
I plan to have a fix for this before December. An issue has been created in tibber-api to address this.

**Comment by kuseman** [comment]
Any news on this?

**Comment by bisand** [comment]
This has been resolved a couple of weeks ago. Please create a new issue if you experience any problems.
Thanks!
