### ISSUE TITLE
Weird newRelicLicenseKey response

### ISSUE THREAD

**Issue by kuseman** [bisand/node-red-contrib-tibber-api#61]
Hi,

Started to get this response from the tibber feed today:

"A connection error occurred: {"type":"connection_error","payload":{"message":"Cannot read properties of undefined (reading 'newRelicLicenseKey')"}}"

Have tried a new access-token from tibber but no luck.

Using version:  2.7.1

**Comment by riksarchen** [comment]
Same issue for me. Began at 12:13 UTC (+00:00)

**Comment by martinsund999** [comment]
Same issue for me. Works in Tibber Developer Explorer.

**Comment by CrowJay** [comment]
Same issue as well, got last update a bit later than reported above, 12:17 UTC

**Comment by kuseman** [comment]
Got Home-assistant working by changing the wss-endpoint to wss://websocket-api.tibber.com/v1-beta/gql/subscriptions
However doing the same change in node-red feed-node doesn't work.

Anyone know what more to be done?

**Comment by sebchalmers** [comment]
I sent an email directly to Tibber to report the problem and the complaints on Git. Historically they care about having a cleanly working system for everyone. Let's see if that is still the case.

**Comment by riksarchen** [comment]
My tibber just connected again. Did nothing. Data was transmitted again at 19.26 utc

**Comment by sebchalmers** [comment]
The good thing with Tibber is that they care about fixing stuff when things go wrong. Response from them at 20:30 local time:

"Hi!Thanks for contacting us. We have reported the issues and it should be working again now.Can you please try and then get back to me?"

**Comment by riksarchen** [comment]
Good job by tibber to a quick fix. 

But to avoid this in future, is it possible to have it local instead through Tibber api?

**Comment by riksarchen** [comment]
Now I get a 503 error instead... :| anyone else?

**Comment by ffbbh** [comment]
Me too, support says, API-guys are working on the issue...

**Comment by bisand** [comment]
It seems like this has been resolved
