### ISSUE TITLE
Support for sending meter readings...

### ISSUE THREAD

**Issue by Snille** [bisand/node-red-contrib-tibber-api#65]
Hi, this may already be possible, I'm not yet so familiar with Node Red...
The scenario is this: I set up my Pulse to report directly to Home Assistant via MQTT. The reson for this is that the Tibber integration (or possibly the Tibber API) is unreliable and hangs from time to time. So, it's better to not fetch the usage data from the Tibber API.
The problem is that now I don't get the "real time" information of watt usage and phases in the Tibber App any more.
So, the question is, is it possible to send that data from HA to Tibbers API using this? if yes, how?
If I look in the "API-Development Documentation" [here](https://developer.tibber.com/docs/reference#meterreadinginput) it looks like it would be possible... But I'm not sure if it is?

Best regards Erik

**Comment by bisand** [comment]
Hi, and sorry for the late reply.
I am not sure I understand what you mean. If you do no longer receive real time information in the Tibber app, you should contact Tibber customer support and see if they can re-eanble it again. But if you already have the real time information enabled in the Tibber app, you should be able to get that via the TibberFeed component in this node-red module. See screenshots below. As far as I know, the real time consumption is only available via TibberFeed, not TibberQuery

![TibberFeed](https://user-images.githubusercontent.com/376963/211465493-8643ab90-1e68-40c4-b839-1d146b89086c.png) ![VoltageCurrent](https://user-images.githubusercontent.com/376963/211465506-ef44327c-f280-4c86-928d-4ea18bb94433.png)

The feed contains voltage and current from each phase. From that you can calculate power by using Ohm's law: Power = Voltage * Current (P = U * I)

Exampel from the screenshot on L1: 
P = 234.3 _Volt_ * 22.4 _Ampere_
P = 5248.32 _Watt_

Hope this answers your question.

Thanks!

**Comment by Snille** [comment]
Hi! I sort of gave up on "real time" monitoring for now... But I'll try to explain... :)
I have a Pulse device connected to the P1 port on my Meter. Usually, when you set it up, you make it report the "real time" usage to Tibber directly (I'm guessing using their API in the background), then you can see the "real time" (10 second intervalls) usage from your meter in the Tibber app. But if you don't have a Pulse device reporting to Tibber, I at least can only see hourly reports of usage.

However, because of (previous) issues with the [Tibber-Integration](https://www.home-assistant.io/integrations/tibber) (not your Node-Red integration) I decided to not let the Pulse device report my usage to Tibbers API, instead let it report directly to Home Assistent using [this integration](https://github.com/toreamun/amshan-homeassistant). This resulted in that I lost the "real time" (10 second reading) in the Tibber app (because they now only get the readings from the grid-owner).

So, the question where, can I use Home Assistant to report the "real time" usage data (that I get from the Pulse device in the AMSHAN integration sensor) and send that to Tibber (via your Node-Red API connection) and there by getting the "real time" usage reading back in the Tibber app again...

I hope this made more sense then the first post... :)

**Comment by bisand** [comment]
A-ha! Now I think I understand.

From what I can see, the only changes (mutations) you can do through the API is described in the table below, taken from the Tibber documentation. The closest thing to what you want is sendMeterReading, which only allows you to send number of consumed KWh (energy) from your meter, not the current power usage (W)

If you want to test it, you can "inject" a mutation as a string into the tibber-query node like the example below.
**Command:**
``` GQL
mutation{
  sendMeterReading(input: {
    homeId: "96a14971-525a-4420-aae9-e5aedaa129ff",
    time: "2022-01-10T12:00:00",
    reading: 10000
  }){
    homeId
    time
    reading
  }
}
```
**Node-Red flow:**
![image](https://user-images.githubusercontent.com/376963/211526679-700d9913-369f-4a75-80f3-4ff3b64e1b9b.png)
![image](https://user-images.githubusercontent.com/376963/211528893-f44ef6bb-57d6-43fc-a946-b377758674ef.png)


[Mutation (RootMutation)](https://developer.tibber.com/docs/reference#mutation)

Field | Argument | Type | Description
-- | -- | -- | --
sendMeterReading | MeterReadingResponse! | Send meter reading for home (only available for Norwegian users)
input | MeterReadingInput! |  
updateHome | Home! | Update home information
input | UpdateHomeInput! |  
sendPushNotification | PushNotificationResponse! | Send notification to Tibber app on registered devices
input | PushNotificationInput! |  

_PS! Disclaimer: I have not tested it myself on my real setup at home. Using the demo token will not allow you to send mutations._
