### ISSUE TITLE
What is the homeID?

### ISSUE THREAD

**Issue by Apacalipto** [bisand/node-red-contrib-tibber-api#75]
Hi,

Hope you can help me. 

What is the HomeID field for? I can't find it.
I just pasted my API key for now, but i'm a bit confused by it.

I am able to retrieve daily energy prices now. 

getHomesComplete() also works.

But with getTomorrowsEnergyPrices(homeid), I get an empty response. 

Thank you for making this application! 👍🏻

**Comment by bisand** [comment]
The HomeID is the ID of your home(s). This is used to identify a particular home. You can find the homeID of your homes by calling getHomesComplete(). That response should include all the information you need about your homes/installations.

**Comment by Apacalipto** [comment]
Got it. Thanks for explaining!
