### ISSUE TITLE
tibber-feed node keeps saying "connecting"

### ISSUE THREAD

**Issue by apelders** [bisand/node-red-contrib-tibber-api#78]
I updated my nodered stack with the latest version of nod-red-contrib-tibber-api.
I configured with my Home id.
Also the tibber-api-endpoint node I configured with the following parameters:
GraphQL Endpoint: https://websocket-api.tibber.com/v1-beta/gql
Access Token: <my token from https://developer.tibber.com/settings/access-token>
Connection Timeout: 30
Feed Timeout: 60
Request Timeout: 30

The tibber-feed-node is still saying "connecting" so I think it is a bug.
I tried some queries that I want to make on https://developer.tibber.com/explorer
There I got proper responses
Is this a bug or do you have some diagnostic suggestions for me.

**Comment by apelders** [comment]
That's what I had inittialy, but after reading https://developer.tibber.com/docs/overview#breaking-websocket-change I thought I should follow up on this.
So both are not working for me.
What can I do more to pinpoint the issue?

**Comment by apelders** [comment]
Good news. Node tibber-query seems to work. I receive data when I do a query.
But the tibber-feed node still reports "connecting".
I don't know if this should be "connected" or how long it takes before it will connect or respond with data.

**Comment by bisand** [comment]
The following config works for me. Remember that the feed url should not be specified, just the query url. The feed url is automatically retrieved by the component.
![image](https://user-images.githubusercontent.com/376963/226922362-d641265e-ca6b-452b-a607-9ccd30e9474b.png)

**Comment by apelders** [comment]
I think I understand it now.
Tibber feed is used when you have a tibber pulse device.
I don't have such a device so connecting is not possible then.
![image](https://user-images.githubusercontent.com/74110838/227047962-2ca8e756-6b7f-4e48-8cbd-f851fc246c60.png)

**Comment by apelders** [comment]
Issue can be closed. My queries are responding fine.

**Comment by apelders** [comment]
Hi André,
In the mean time I bought a Tibber Pulse and connected it to the P1 port.
In the https://developer.tibber.com/explorer I used the Real time subscription template with my own token and I was able to see my consumption live.
Also in the app I was able to activate the Tibber Pulse icon and it reported my current consumption.
However, when I want to see my live measurement in Node-RED, I expected to see this data when I use the Tibber feed node.
![image](https://user-images.githubusercontent.com/74110838/227791243-21ab23a9-6f9b-421c-b0c4-a1b9f012c556.png)
This is how I setup the endpoint node and it is working perfectly for tibber-queries.
![image](https://user-images.githubusercontent.com/74110838/227791427-96b29fe9-054b-4407-a5bb-33819275ab85.png)
And this is how I setup the feed node.
It keeps saying "connecting"and no output seen yet.
Are there other prerequisites for this node?

**Comment by bisand** [comment]
The setup you have should be sufficient. Have you double checked that you have the correct HomeID? You might also find more detailed logging in the Node-Red logs.

**Comment by apelders** [comment]
I looked at the logging:
![image](https://user-images.githubusercontent.com/74110838/228002749-2600bc76-926a-4d1f-95f7-52b1593a38ff.png)
Indeed some pointers that there are too many listeners, so I removed my queries from the flow and restarted node-RED.
Now Tibber-feed says "connected". So I had too many listeners.
Can you explain how I can increase the MaxListeners that the logging is complaining about?

**Comment by bisand** [comment]
Good catch.
The TibberFeed is designed to only have one shared connection per «api-key&homeid». This could actually be a bug. I will have to do some research before I can conclude on anything.
Are you able to export the flow that causes that problem. It would be nice to be see if I can reproduce it on my end.

**Comment by apelders** [comment]
Unfortunately I was not able to reproduce, even after restoring the original flow (homeID removed).
`
[{"id":"683fd7.e63da028","type":"tab","label":"Tibber","disabled":false,"info":""},{"id":"4d0b020a.94fbac","type":"debug","z":"683fd7.e63da028","name":"","active":false,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":590,"y":360,"wires":[]},{"id":"983cd36.d80383","type":"inject","z":"683fd7.e63da028","name":"Get Home Id","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{   viewer {     homes {       id       address {         address1         address2         address3         postalCode         city         country         latitude         longitude                }     }   } }","payloadType":"str","x":150,"y":100,"wires":[["e728c1c02e6ee95f"]]},{"id":"4a25248d.5e506c","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":550,"y":100,"wires":[]},{"id":"e0404127.1a2f8","type":"http request","z":"683fd7.e63da028","name":"","method":"POST","ret":"txt","paytoqs":"ignore","url":"http://influxdb:8086/write?precision=s&consistency=any&db=domotica_db","tls":"","persist":false,"proxy":"","insecureHTTPParser":false,"authType":"","senderr":false,"headers":[],"x":590,"y":300,"wires":[["4d0b020a.94fbac"]]},{"id":"1491f46.f317b0c","type":"function","z":"683fd7.e63da028","name":"Transform payload","func":"let p = msg.payload;\n\nif (!p.voltagePhase1)\n    return null;\n\nfor (var prop in p) {\n    if (!p[prop])\n        p[prop] = 0;\n}\n\n// Meassurement\nlet data = \"power\";\n\n// Tag set\ndata += \",location=tibber/energy\";\ndata += \",currency=\" + p.currency;\n\n// Field set\ndata += \" power=\" + p.power;\ndata += \",lastMeterConsumption=\" + p.lastMeterConsumption;\ndata += \",accumulatedConsumption=\" + p.accumulatedConsumption;\ndata += \",accumulatedProduction=\" + p.accumulatedProduction;\ndata += \",accumulatedCost=\" + p.accumulatedCost;\ndata += \",accumulatedReward=\" + p.accumulatedReward;\ndata += \",minPower=\" + p.minPower;\ndata += \",averagePower=\" + p.averagePower;\ndata += \",maxPower=\" + p.maxPower;\ndata += \",powerProduction=\" + p.powerProduction;\ndata += \",minPowerProduction=\" + p.minPowerProduction;\ndata += \",maxPowerProduction=\" + p.maxPowerProduction;\ndata += \",lastMeterProduction=\" + p.lastMeterProduction;\ndata += \",powerFactor=\" + p.powerFactor;\ndata += \",voltagePhase1=\" + p.voltagePhase1;\ndata += \",voltagePhase2=\" + p.voltagePhase2;\ndata += \",voltagePhase3=\" + p.voltagePhase3;\ndata += \",currentPhase1=\" + p.currentPhase1;\ndata += \",currentPhase2=\" + p.currentPhase2;\ndata += \",currentPhase3=\" + p.currentPhase3;\n\nmsg.payload = data;\n\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":390,"y":300,"wires":[["e0404127.1a2f8","700d5b2b18e6f259"]]},{"id":"4286466c.a02e08","type":"http request","z":"683fd7.e63da028","name":"","method":"POST","ret":"txt","paytoqs":"ignore","url":"http://influxdb:8086/query?q=CREATE%20DATABASE%20%22test%22","tls":"","persist":false,"proxy":"","insecureHTTPParser":false,"authType":"","senderr":false,"headers":[],"credentials":{},"x":370,"y":40,"wires":[["d102d972.8fb0c8"]]},{"id":"b24ffef4.c3ca","type":"inject","z":"683fd7.e63da028","name":"Create test database","props":[{"p":"payload","v":"","vt":"str"},{"p":"topic","v":"","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"str","x":170,"y":40,"wires":[["4286466c.a02e08"]]},{"id":"d102d972.8fb0c8","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":550,"y":40,"wires":[]},{"id":"425b3d0d.8f10d4","type":"inject","z":"683fd7.e63da028","name":"Daily energy prices","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"30 00 * * *","once":false,"onceDelay":0.1,"topic":"","payload":"{   viewer {     homes {       currentSubscription {         priceInfo {           today {             total             energy             tax             startsAt             currency             level           }         }       }     }   } }","payloadType":"str","x":180,"y":180,"wires":[["9d7d2f51edc4303a"]]},{"id":"810b8faa.9656a","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":550,"y":240,"wires":[]},{"id":"9f49c320.526db","type":"function","z":"683fd7.e63da028","name":"Transform energy price","func":"let pl = msg.payload;\n\nlet prices = pl.viewer.homes[0].currentSubscription.priceInfo.today;\n\n// Meassurement\nlet data = \"\";\n\nfor(let i = 0; i < prices.length; i++)\n{\n    let p = prices[i];\n    data += \"tibber/energy\";\n\n    // Tag set\n    data += \",location=test\";\n    data += \",currency=\" + p.currency;\n    \n    // Field set\n    data += \" total=\" + p.total;\n    data += \",energy=\" + p.energy;\n    data += \",tax=\" + p.tax;\n    data += \",level=\\\"\" + p.level + \"\\\"\";\n    data += \" \" + new Date(p.startsAt).getTime() / 1000 + \"\";\n    data += \"\\n\";\n}\n\nmsg.payload = data;\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":590,"y":180,"wires":[["c478abbd.5715e8","56a06f4d8be15ce0"]]},{"id":"c478abbd.5715e8","type":"http request","z":"683fd7.e63da028","name":"","method":"POST","ret":"txt","paytoqs":"ignore","url":"http://influxdb:8086/write?precision=s&consistency=any&db=domotica_db","tls":"","persist":false,"proxy":"","insecureHTTPParser":false,"authType":"","senderr":false,"headers":[],"x":370,"y":240,"wires":[["810b8faa.9656a"]]},{"id":"7473a7df91b7c1ff","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":810,"y":140,"wires":[]},{"id":"f561d6e247af0cd4","type":"inject","z":"683fd7.e63da028","name":"Logged in user","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"30 00 * * *","once":false,"onceDelay":0.1,"topic":"","payload":"{   viewer {     name   } }","payloadType":"str","x":160,"y":540,"wires":[["51f03db6888434e9"]]},{"id":"90a3027c3f4e4ac9","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":650,"y":540,"wires":[]},{"id":"7265ecdf0c9ec72a","type":"inject","z":"683fd7.e63da028","name":"Homes","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"30 00 * * *","once":false,"onceDelay":0.1,"topic":"","payload":"{   viewer {     homes {       address {         address1         address2         address3         postalCode         city         country         latitude         longitude       }     }   } }","payloadType":"str","x":140,"y":640,"wires":[["c0e2894f49675fc3"]]},{"id":"2f085029de2a59f8","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":650,"y":640,"wires":[]},{"id":"d4153bcc66c19fa7","type":"inject","z":"683fd7.e63da028","name":"Current energy prices","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"30 00 * * *","once":false,"onceDelay":0.1,"topic":"","payload":"{   viewer {     homes {       currentSubscription{         priceInfo{           current{             total             energy             tax             startsAt           }           today {             total             energy             tax             startsAt           }           tomorrow {             total             energy             tax             startsAt           }         }       }     }   } }","payloadType":"str","x":180,"y":720,"wires":[["723bb4a193497c1b"]]},{"id":"4942b46e161e3650","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":650,"y":720,"wires":[]},{"id":"fe79b8c7886db92a","type":"inject","z":"683fd7.e63da028","name":"Consumption","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"30 00 * * *","once":false,"onceDelay":0.1,"topic":"","payload":"{   viewer {     homes {       consumption(resolution: HOURLY, last: 100) {         nodes {           from           to           cost           unitPrice           unitPriceVAT           consumption           consumptionUnit         }       }     }   } }","payloadType":"str","x":160,"y":800,"wires":[["5a06b27a085706c3"]]},{"id":"55e88addd0a4165a","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":650,"y":800,"wires":[]},{"id":"17af5f3daa240b69","type":"inject","z":"683fd7.e63da028","name":"Homes/Price/Consumption","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"30 00 * * *","once":false,"onceDelay":0.1,"topic":"","payload":"{   viewer {     homes {       timeZone       address {         address1         postalCode         city       }       owner {         firstName         lastName         contactInfo {           email           mobile         }       }       consumption(resolution: HOURLY, last: 10) {         nodes {           from           to           cost           unitPrice           unitPriceVAT           consumption           consumptionUnit         }       }       currentSubscription {         status         priceInfo {           current {             total             energy             tax             startsAt           }         }       }     }   } }","payloadType":"str","x":200,"y":880,"wires":[["32fcdbdcc38338b6"]]},{"id":"c8616ad58260a089","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":650,"y":880,"wires":[]},{"id":"56a06f4d8be15ce0","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":830,"y":220,"wires":[]},{"id":"e728c1c02e6ee95f","type":"tibber-query","z":"683fd7.e63da028","name":"","active":true,"apiEndpointRef":"24a5e1d6b98b116a","x":370,"y":100,"wires":[["4a25248d.5e506c"]]},{"id":"9d7d2f51edc4303a","type":"tibber-query","z":"683fd7.e63da028","name":"","active":true,"apiEndpointRef":"24a5e1d6b98b116a","x":390,"y":180,"wires":[["9f49c320.526db","7473a7df91b7c1ff"]]},{"id":"51f03db6888434e9","type":"tibber-query","z":"683fd7.e63da028","name":"","active":true,"apiEndpointRef":"24a5e1d6b98b116a","x":410,"y":540,"wires":[["90a3027c3f4e4ac9"]]},{"id":"c0e2894f49675fc3","type":"tibber-query","z":"683fd7.e63da028","name":"","active":true,"apiEndpointRef":"24a5e1d6b98b116a","x":410,"y":640,"wires":[["2f085029de2a59f8"]]},{"id":"723bb4a193497c1b","type":"tibber-query","z":"683fd7.e63da028","name":"","active":true,"apiEndpointRef":"24a5e1d6b98b116a","x":410,"y":720,"wires":[["4942b46e161e3650"]]},{"id":"5a06b27a085706c3","type":"tibber-query","z":"683fd7.e63da028","name":"","active":true,"apiEndpointRef":"24a5e1d6b98b116a","x":410,"y":800,"wires":[["55e88addd0a4165a"]]},{"id":"32fcdbdcc38338b6","type":"tibber-query","z":"683fd7.e63da028","name":"","active":true,"apiEndpointRef":"24a5e1d6b98b116a","x":410,"y":880,"wires":[["c8616ad58260a089"]]},{"id":"ab2d599a.077738","type":"tibber-query","z":"683fd7.e63da028","name":"Get Tibber prices","active":true,"apiEndpointRef":"24a5e1d6b98b116a","x":1270,"y":460,"wires":[["0ef929fde193cf4d","9a8c06e36f91f2f4"]]},{"id":"4f11b5ae.4cc22c","type":"inject","z":"683fd7.e63da028","name":"Refresh","props":[{"p":"payload"}],"repeat":"3600","crontab":"","once":true,"onceDelay":"1","topic":"","payload":"{   viewer {     homes {       currentSubscription{         priceInfo{           today {             total             startsAt           }           tomorrow {             total             startsAt           }         }       }     }   } }","payloadType":"str","x":1080,"y":460,"wires":[["ab2d599a.077738"]]},{"id":"5b6be1568744c6cf","type":"ps-strategy-best-save","z":"683fd7.e63da028","name":"Best Save","maxHoursToSaveInSequence":"5","minHoursOnAfterMaxSequenceSaved":"1","minSaving":"0.05","sendCurrentValueWhenRescheduling":true,"outputValueForOn":"true","outputValueForOff":"true","outputValueForOntype":"bool","outputValueForOfftype":"bool","outputIfNoSchedule":"true","contextStorage":"memory","x":1290,"y":520,"wires":[["041a5ee7594c1e87"],["048581b177e5e233"],["6c2a93d5358b6ac6"]]},{"id":"0ef929fde193cf4d","type":"ps-receive-price","z":"683fd7.e63da028","name":"Price Receiver","x":1080,"y":520,"wires":[["5b6be1568744c6cf"]]},{"id":"9a8c06e36f91f2f4","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":1570,"y":440,"wires":[]},{"id":"041a5ee7594c1e87","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":1570,"y":500,"wires":[]},{"id":"048581b177e5e233","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":1570,"y":560,"wires":[]},{"id":"6c2a93d5358b6ac6","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":1570,"y":620,"wires":[]},{"id":"df29bbbba762ba22","type":"inject","z":"683fd7.e63da028","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{   viewer {     homes {       consumption(resolution: HOURLY, last: 10) {         nodes {           from           to           cost           unitPrice           unitPriceVAT           consumption           consumptionUnit         }       }       currentSubscription {         priceInfo {           current {             total             energy             tax             startsAt           }         }       }     }   } }","payloadType":"str","x":150,"y":980,"wires":[["0c96fae6b809919d"]]},{"id":"0c96fae6b809919d","type":"tibber-query","z":"683fd7.e63da028","name":"","active":true,"apiEndpointRef":"24a5e1d6b98b116a","x":330,"y":980,"wires":[["719b13a30161031a"]]},{"id":"719b13a30161031a","type":"debug","z":"683fd7.e63da028","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":550,"y":980,"wires":[]},{"id":"700d5b2b18e6f259","type":"debug","z":"683fd7.e63da028","name":"","active":false,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":490,"y":420,"wires":[]},{"id":"07d348fb59b8cb10","type":"tibber-feed","z":"683fd7.e63da028","name":"Tibber","active":true,"apiEndpointRef":"24a5e1d6b98b116a","homeId":"xxx","timestamp":"1","power":"1","lastMeterConsumption":false,"accumulatedConsumption":"1","accumulatedProduction":false,"accumulatedConsumptionLastHour":false,"accumulatedProductionLastHour":false,"accumulatedCost":"1","accumulatedReward":false,"currency":false,"minPower":false,"averagePower":false,"maxPower":false,"powerProduction":false,"minPowerProduction":false,"maxPowerProduction":false,"lastMeterProduction":false,"powerFactor":false,"voltagePhase1":true,"voltagePhase2":false,"voltagePhase3":false,"currentL1":false,"currentL2":false,"currentL3":false,"signalStrength":false,"x":150,"y":300,"wires":[["1491f46.f317b0c"]]},{"id":"24a5e1d6b98b116a","type":"tibber-api-endpoint","queryUrl":"https://api.tibber.com/v1-beta/gql","feedConnectionTimeout":"30","feedTimeout":"60","queryRequestTimeout":"30","name":"Tibber"}]
`
