### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by raolss** [bisand/node-red-contrib-tibber-api#83]
I might be mistaking but it seems the Tibber-Query node does not throw errors according to the node red standard. https://nodered.org/docs/user-guide/handling-errors

**Comment by bisand** [comment]
That might be correct, but do you have any examples where the error handling is incorrect? 😊

**Comment by raolss** [comment]
Hi
It can be reproduced by using an incorrect API token to invoke an error. Debug will show an object with a property, "errors". A catch node isn't able to catch the error. 

Does that make sense?

**Comment by bisand** [comment]
Ok, thanks! I will try it out and hopefully have a fix for it not to far from now. Feel free to submit a pull reauest if you know how to fix. Currently I’m on vacation, so it could take a few weeks..

**Comment by raolss** [comment]
Hi
My coding skills are limited. Do you know in what file it is handled?
