### ISSUE TITLE
syslog / daemon.log get full of errors

### ISSUE THREAD

**Issue by Becker884** [bisand/node-red-contrib-tibber-api#84]
Hi, I´m using node-red-contrib-tibber-api without problems, but something internal seems to be wrong, my micro-sd card has been written full (20GB) with these messages from Node-Red:
`[info] [tibber-feed] Message contains unexpected id and will be ignored.
Jul  2 14:56:09 raspberrypi Node-RED[381]: {"id":"2","type":"next","payload":{"data":{"liveMeasurement":{"timestamp":"2023-07-02T14:56:07.000+02:00","power":114,"lastMeterConsumption":1957.33534159,"accumulatedConsumption":1.611493,"accumulatedProduction":0,"accumulatedConsumptionLastHour":0.140509,"accumulatedProductionLastHour":0,"accumulatedCost":0.062052,"accumulatedReward":null,"currency":"EUR","minPower":30,"averagePower":107.9,"maxPower":1263,"powerProduction":null,"minPowerProduction":null,"maxPowerProduction":null,"lastMeterProduction":-1,"powerFactor":null,"voltagePhase1":234.4,"voltagePhase2":234.4,"voltagePhase3":236.7,"currentL1":null,"currentL2":null,"currentL3":null,"signalStrength":null}}}}
Jul  2 14:56:11 raspberrypi Node-RED[381]: 2 Jul 14:56:11 - [info] [tibber-feed] Message contains unexpected id and will be ignored.
Jul  2 14:56:11 raspberrypi Node-RED[381]:  ...

Jul  2 22:35:42 raspberrypi Node-RED[381]: {"id":"15","type":"next","payload":{"data":{"liveMeasurement":{"timestamp":"2023-07-02T22:35:42.000+02:00","power":2,"lastMeterConsumption":11325.2660531,"accumulatedConsumption":27.372036,"accumulatedProduction":71.75658,"accumulatedConsumptionLastHour":0.006142,"accumulatedProductionLastHour":0.004312,"accumulatedCost":-11.931418,"accumulatedReward":null,"currency":"EUR","minPower":-16881,"averagePower":1211.3,"maxPower":26490,"powerProduction":null,"minPowerProduction":0,"maxPowerProduction":25051,"lastMeterProduction":39868.3160149,"powerFactor":null,"voltagePhase1":null,"voltagePhase2":null,"voltagePhase3":null,"currentL1":null,"currentL2":null,"currentL3":null,"signalStrength":null}}}}
Jul  2 22:35:42 raspberrypi Node-RED[381]: 2 Jul 22:35:42 - [info] [tibber-feed:Easymeter] Message contains unexpected id and will be ignored.
Jul  2 22:35:42 raspberrypi Node-RED[381]: {"id":"19","type":"next","payload":{"data":{"liveMeasurement":{"timestamp":"2023-07-02T22:35:42.000+02:00","power":2,"lastMeterConsumption":11325.2660531,"accumulatedConsumption":27.372036,"accumulatedProduction":71.75658,"accumulatedConsumptionLastHour":0.006142,"accumulatedProductionLastHour":0.004312,"accumulatedCost":-11.931418,"accumulatedReward":null,"currency":"EUR","minPower":-16881,"averagePower":1211.3,"maxPower":26490,"powerProduction":null,"minPowerProduction":0,"maxPowerProduction":25051,"lastMeterProduction":39868.3160149,"powerFactor":null,"voltagePhase1":null,"voltagePhase2":null,"voltagePhase3":null,"currentL1":null,"currentL2":null,"currentL3":null,"signalStrength":null}}}}
Jul  2 22:35:44 raspberrypi Node-RED[381]: 2 Jul 22:35:44 - [info] [tibber-feed:Easymeter] Message contains unexpected id and will be ignored.
Jul  2 22:35:44 raspberrypi Node-RED[381]: {"id":"22","type":"next","payload":{"data":{"liveMeasurement":{"timestamp":"2023-07-02T22:35:42.000+02:00","power":2,"lastMeterConsumption":11325.2660531,"accumulatedConsumption":27.372036,"accumulatedProduction":71.75658,"accumulatedConsumptionLastHour":0.006142,"accumulatedProductionLastHour":0.004312,"accumulatedCost":-11.931418,"accumulatedReward":null,"currency":"EUR","minPower":-16881,"averagePower":1211.3,"maxPower":26490,"powerProduction":null,"minPowerProduction":0,"maxPowerProduction":25051,"lastMeterProduction":39868.3160149,"powerFactor":null,"voltagePhase1":null,"voltagePhase2":null,"voltagePhase3":null,"currentL1":null,"currentL2":null,"currentL3":null,"signalStrength":null}}}}
Jul  2 22:35:44 raspberrypi Node-RED[381]: 2 Jul 22:35:44 - [info] [tibber-feed:Easymeter] Message contains unexpected id and will be ignored.
Jul  2 22:35:44 raspberrypi Node-RED[381]: {"id":"13","type":"next","payload":{"data":{"liveMeasurement":{"timestamp":"2023-07-02T22:35:42.000+02:00","power":2,"lastMeterConsumption":11325.2660531,"accumulatedConsumption":27.372036,"accumulatedProduction":71.75658,"accumulatedConsumptionLastHour":0.006142,"accumulatedProductionLastHour":0.004312,"accumulatedCost":-11.931418,"accumulatedReward":null,"currency":"EUR","minPower":-16881,"averagePower":1211.3,"maxPower":26490,"powerProduction":null,"minPowerProduction":0,"maxPowerProduction":25051,"lastMeterProduction":39868.3160149,"powerFactor":null,"voltagePhase1":null,"voltagePhase2":null,"voltagePhase3":null,"currentL1":null,"currentL2":null,"currentL3":null,"signalStrength":null}}}}
Jul  2 22:35:44 raspberrypi Node-RED[381]: 2 Jul 22:35:44 - [info] [tibber-feed:Easymeter] Message contains unexpected id and will be ignored.
Jul  2 22:35:44 raspberrypi Node-RED[381]: {"id":"7","type":"next","payload":{"data":{"liveMeasurement":{"timestamp":"2023-07-02T22:35:42.000+02:00","power":2,"lastMeterConsumption":11325.2660531,"accumulatedConsumption":27.372036,"accumulatedProduction":71.75658,"accumulatedConsumptionLastHour":0.006142,"accumulatedProductionLastHour":0.004312,"accumulatedCost":-11.931418,"accumulatedReward":null,"currency":"EUR","minPower":-16881,"averagePower":1211.3,"maxPower":26490,"powerProduction":null,"minPowerProduction":0,"maxPowerProduction":25051,"lastMeterProduction":39868.3160149,"powerFactor":null,"voltagePhase1":null,"voltagePhase2":null,"voltagePhase3":null,"currentL1":null,"currentL2":null,"currentL3":null,"signalStrength":null}}}}
Jul  2 22:35:45 raspberrypi Node-RED[381]: 2 Jul 22:35:45 - [info] [tibber-feed:Easymeter] Message contains unexpected id and will be ignored.
Jul  2 22:35:45 raspberrypi Node-RED[381]: {"id":"17","type":"next","payload":{"data":{"liveMeasurement":{"timestamp":"2023-07-02T22:35:45.000+02:00","power":0,"lastMeterConsumption":11325.2660594,"accumulatedConsumption":27.372043,"accumulatedProduction":71.756581,"accumulatedConsumptionLastHour":0.006149,"accumulatedProductionLastHour":0.004312,"accumulatedCost":-11.931416,"accumulatedReward":null,"currency":"EUR","minPower":-16881,"averagePower":1211.2,"maxPower":26490,"powerProduction":5,"minPowerProduction":0,"maxPowerProduction":25051,"lastMeterProduction":39868.3160154,"powerFactor":null,"voltagePhase1":null,"voltagePhase2":null,"voltagePhase3":null,"currentL1":null,"currentL2":null,"currentL3":null,"signalStrength":null}}}}
Jul  2 22:35:45 raspberrypi Node-RED[381]: 2 Jul 22:35:45 - [info] [tibber-feed:Easymeter] Message contains unexpected id and will be ignored.
Jul  2 22:35:45 raspberrypi Node-RED[381]: {"id":"15","type":"next","payload":{"data":{"liveMeasurement":{"timestamp":"2023-07-02T22:35:45.000+02:00","power":0,"lastMeterConsumption":11325.2660594,"accumulatedConsumption":27.372043,"accumulatedProduction":71.756581,"accumulatedConsumptionLastHour":0.006149,"accumulatedProductionLastHour":0.004312,"accumulatedCost":-11.931416,"accumulatedReward":null,"currency":"EUR","minPower":-16881,"averagePower":1211.2,"maxPower":26490,"powerProduction":5,"minPowerProduction":0,"maxPowerProduction":25051,"lastMeterProduction":39868.3160154,"powerFactor":null,"voltagePhase1":null,"voltagePhase2":null,"voltagePhase3":null,"currentL1":null,"currentL2":null,"currentL3":null,"signalStrength":null}}}}
Jul  2 22:35:45 raspberrypi Node-RED[381]: 2 Jul 22:35:45 - [info] [tibber-feed:Easymeter] Message contains unexpected id and will be ignored.
Jul  2 22:35:45 raspberrypi Node-RED[381]: {"id":"19","type":"next","payload":{"data":{"liveMeasurement":{"timestamp":"2023-07-02T22:35:45.000+02:00","power":0,"lastMeterConsumption":11325.2660594,"accumulatedConsumption":27.372043,"accumulatedProduction":71.756581,"accumulatedConsumptionLastHour":0.006149,"accumulatedProductionLastHour":0.004312,"accumulatedCost":-11.931416,"accumulatedReward":null,"currency":"EUR","minPower":-16881,"averagePower":1211.2,"maxPower":26490,"powerProduction":5,"minPowerProduction":0,"maxPowerProduction":25051,"lastMeterProduction":39868.3160154,"powerFactor":null,"voltagePhase1":null,"voltagePhase2":null,"voltagePhase3":null,"currentL1":null,"currentL2":null,"currentL3":null,"signalStrength":null}}}}`

In debug there is no error showing, everything is fine.
Any idea what´s going wrong with the tibber live feed, who is writing my sd-card completly full ?

**Comment by bisand** [comment]
It seems to be some unnecessary logging causing this. Let me take a look at it and get back to you.

**Comment by Becker884** [comment]
is it also possible to reduce the polling interval from 2s to 5s or 10s?

**Comment by bisand** [comment]
It’s not polling. The component gets its data from a websocket stream. You would have to apply logic in between TibberFeed component and the rest of your flow if you want to throttle the speed.

**Comment by Becker884** [comment]
Do you know how to query the live meter by a function in Node Red?

`[{"id":"59b9af5caf250a13","type":"inject","z":"bc38480e05df57a2","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":180,"y":260,"wires":[["e9b6109e3d6e61db"]]},{"id":"c692182f3abaf363","type":"debug","z":"bc38480e05df57a2","name":"debug 349","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":650,"y":260,"wires":[]},{"id":"8368f0c1781153d3","type":"http request","z":"bc38480e05df57a2","name":"","method":"use","ret":"obj","paytoqs":"ignore","url":"","tls":"","persist":false,"proxy":"","insecureHTTPParser":false,"authType":"","senderr":false,"headers":[],"x":490,"y":260,"wires":[["c692182f3abaf363"]]},{"id":"e9b6109e3d6e61db","type":"function","z":"bc38480e05df57a2","name":"function 164","func":"const headers = {}\nconst token = \"5K4MVS-OjfWhK_4yrjOlFe1F6kJXPVf7eQYggo8ebAE\"\nheaders[\"Content-Type\"] = \"application/json\"\nheaders[\"Authorization\"] = `Bearer ${token}`\nmsg.method = \"POST\"\nmsg.headers = headers\nmsg.url = \"https://api.tibber.com/v1-beta/gql\"\nmsg.payload = { \"query\": \"{viewer {homes {currentSubscription {priceInfo {current {total energy tax startsAt }}}}}}\" }\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":330,"y":260,"wires":[["8368f0c1781153d3"]]}]`
this works, but I dont get the function for the pulse:
`const headers = {}
const token = "xy"
headers["Content-Type"] = "application/json"
headers["Authorization"] = `Bearer ${token}`
msg.method = "POST"
msg.headers = headers
msg.url = "https://api.tibber.com/v1-beta/gql"
msg.payload = { "subscription": "{liveMeasurement(homeId:"xxx") { timestamp power accumulatedConsumption accumulatedCost currency minPower averagePower maxPower }}" }
return msg;`

**Comment by bisand** [comment]
I have released a new version (5.2.2) that should address the logging issue. Hope that solves your issue @Becker884 

From what I know, Tibber only support live measurements from pulse via the websocket connection.

**Comment by Becker884** [comment]
Thank you, log seems to be small
