### ISSUE TITLE
Tibber-feed node stuck in "connecting"

### ISSUE THREAD

**Issue by selstam** [bisand/node-red-contrib-tibber-api#87]
Looks like my tibber feed node is stuck in "connecting" and the logs sees a lot of tries but no success. This started about 14 days ago.

What can I do to debug? I've checked connectivity and it seems to be working correctly.

Log entries:
```
24 Aug 20:20:32 - [info] [tibber-feed:38b028a9.878ca8] Disconnecting from Tibber feed...
24 Aug 20:20:32 - [info] [tibber-feed:38b028a9.878ca8] Done.
24 Aug 20:20:32 - [info] [tibber-feed:38b028a9.878ca8] Preparing to connect to Tibber...
24 Aug 20:20:33 - [info] [tibber-feed:38b028a9.878ca8] Connecting to Tibber...
```

Name resolution works:

```
450a7ab48f2:~$ nslookup api.tibber.com
Non-authoritative answer:
Name:   api.tibber.com
Address: 52.209.255.64
Name:   api.tibber.com
Address: 52.31.25.36
```

... and trying a web request at least reaches the server:

```
450a7ab48f2:~$ curl https://api.tibber.com/v1-beta/gql
{"errors":[{"message":"Context creation failed: no token specified","extensions":{"code":"UNAUTHENTICATED"}}]}
```

**Comment by bisand** [comment]
Have you checked that you still have access to Tibber services. Head over to https://developer.tibber.com and check your credentials and access token in the API explorer.
Please report back on your findings.

**Comment by selstam** [comment]
Yes, that's the first thing I did. Also tested the token in the API explorer to make sure I'd receive a response.

I'll check witch the token and curl fron Inside the docker image to see that's working too.

Any other tips for debugging?

**Comment by Slomo17** [comment]
Same Problem here also with node-red running in a docker container. My log looks a bit different however:

```
9 Sep 17:48:28 - [info] [tibber-feed:3cd217dccee4fa8e] Can connect: false. Last retry: 1694271726409. With backoff for: 3432548 ms.
9 Sep 17:48:29 - [info] [tibber-feed:3cd217dccee4fa8e] Can connect: false. Last retry: 1694271726409. With backoff for: 3432548 ms.
9 Sep 17:48:30 - [info] [tibber-feed:3cd217dccee4fa8e] Can connect: false. Last retry: 1694271726409. With backoff for: 3432548 ms.

```

**Comment by Slomo17** [comment]
Its working now, i think it was a problem with the connection between my pulse and the tibber bridge
