### ISSUE TITLE
node red UI change after ode-red-contrib-tibber-api install

### ISSUE THREAD

**Issue by stasjminister** [bisand/node-red-contrib-tibber-api#89]
I have had this issue for some time, but I finally managed to reproduce it on a vanilla install with just node red and this palette component. I tried with other palette-items(not all..), but managed to reproduce the issue when installing this component and also verified that the issue was gone after it was uninstalled and the server was restarted.

Node red 16.0.2
tibber-api-version 6.0.0 (Issue has been there for over a year)

The issue: 
Before installing the component, the "Call Service Node" (might be affecting other nodes as well, but I have only seen this one affected) has all entities listed vertically beneath each other. It should not be related. But it is still affected..

![image (11)](https://github.com/bisand/node-red-contrib-tibber-api/assets/11752970/a4051205-c5ca-4f25-b7df-f9c554959c2e)

After install, the entities are listed horizontally, creating a long unmanageable list.
![image (7)](https://github.com/bisand/node-red-contrib-tibber-api/assets/11752970/af4f1db3-0e06-4f88-b795-046145a3b5ec)

![image (9)](https://github.com/bisand/node-red-contrib-tibber-api/assets/11752970/40eba11b-5383-4fdd-a6e7-ee7234b0f3a6)

![image (12)](https://github.com/bisand/node-red-contrib-tibber-api/assets/11752970/99b07fa4-9a77-43d5-9960-bee91fd69af4)
![image (10)](https://github.com/bisand/node-red-contrib-tibber-api/assets/11752970/6af505f5-c324-40f5-9c45-b27080b99968)

When uninstalling this component, and restarting the server. The entities are listed horizontally again.
![image (8)](https://github.com/bisand/node-red-contrib-tibber-api/assets/11752970/cfa67d25-8934-4856-b69a-2ad12a70966e)

I have tried to install some other components, but they do not cause this issue. please see images attached for details. 

PS, I have parsed the page code. and found that disabling the "display: inline-block;" corrects the issue. But I do not think this is the right solution, as "display: inline-block;" is present on the working node, when this component is not installed. So this might be a false lead..

.select2-container--nodered .select2-selection--multiple .select2-selection__choice
.select2-container--nodered .select2-selection--multiple .select2-selection__choice {
    border-bottom: 1px solid var(--red-ui-form-input-border-color);
    box-sizing: border-box;
    /* display: inline-block; */
    max-width: 100%;
    overflow: hidden;
    padding: 4px 24px 4px 4px;
    position: relative;
    text-overflow: ellipsis;
    vertical-align: bottom;
    white-space: nowrap;
    width: 100%;
}

**Comment by bisand** [comment]
Thanks for reporting this!
I have published a new version that should address this issue (v6.0.1). The config nodes contained some css styles that might have interfered with other nodes. This has been changed into inline styling and the css has been removed. 
Take it for a spin and let me know if this resolves your issue.
Thanks!
